# Generated by Django 2.2 on 2021-05-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slut',
            new_name='slug',
        ),
    ]
